### PR TITLE
Bump for rails 6.1

### PR DESCRIPTION
**Pull request by aenand**
activesupport and i18n need to be bumped in this repo
to support core moving to rails 6.1.5

[ECS-873](https://spreedly.atlassian.net/browse/ECS-873)

These 6 tests are failing for me on master. I don't think they
are related but if anyone knows more please let me know!
Finished in 0.3323 seconds (files took 0.5297 seconds to load)
628 examples, 6 failures

Please ensure the following is present in your PR:

- [ ] Unit tests for your change
- [ ] Integration tests (if applicable)

Pull requests that are small and limited in scope are most welcome.

### CODE REVIEW

**Comment by apfranzen** [comment]
@aenand these same 6 tests are failing on master for me too, but we haven't seen any errors or warnings running this branch while testing in the Rails 6 Id upgrade. 

@tatsianaclifton do you happen to have any context with these tests from you recent work in a8fd7a4? Because of the deprecated state of this repo, I'm wondering if these tests have not been passing for some time and if it would be ok to leave these tests as not passing?

```
Finished in 0.34606 seconds (files took 0.66315 seconds to load)
628 examples, 6 failures

Failed examples:

rspec ./spec/riak/beefcake_protobuffs_backend/ts_cell_codec_spec.rb:49 # Riak::Client::BeefcakeProtobuffsBackend::TsCellCodec serializing values refuses to serialize big numbers
rspec ./spec/riak/counter_spec.rb:131 # Riak::Counter failure modes doesn't retry on quorum failure
rspec ./spec/riak/counter_spec.rb:126 # Riak::Counter failure modes doesn't retry on timeout
rspec ./spec/riak/map_reduce_spec.rb:370 # Riak::MapReduce adding link phases accepts a hash of options intermingled with the walk spec options
rspec ./spec/riak/map_reduce_spec.rb:347 # Riak::MapReduce adding link phases returns self for chaining
rspec ./spec/riak/beefcake_protobuffs_backend_spec.rb:102 # Riak::Client::BeefcakeProtobuffsBackend secondary index returns no results when no keys or terms are returned
```

**Comment by tatsianaclifton** [comment]
> @aenand these same 6 tests are failing on master for me too, but we haven't seen any errors or warnings running this branch while testing in the Rails 6 Id upgrade.
> 
> @tatsianaclifton do you happen to have any context with these tests from you recent work in [a8fd7a4](https://github.com/spreedly/riak-ruby-client/commit/a8fd7a4e162effcbe97da55b10f645a1475c66ba)? Because of the deprecated state of this repo, I'm wondering if these tests have not been passing for some time and if it would be ok to leave these tests as not passing?
> 
> ```
> Finished in 0.34606 seconds (files took 0.66315 seconds to load)
> 628 examples, 6 failures
> 
> Failed examples:
> 
> rspec ./spec/riak/beefcake_protobuffs_backend/ts_cell_codec_spec.rb:49 # Riak::Client::BeefcakeProtobuffsBackend::TsCellCodec serializing values refuses to serialize big numbers
> rspec ./spec/riak/counter_spec.rb:131 # Riak::Counter failure modes doesn't retry on quorum failure
> rspec ./spec/riak/counter_spec.rb:126 # Riak::Counter failure modes doesn't retry on timeout
> rspec ./spec/riak/map_reduce_spec.rb:370 # Riak::MapReduce adding link phases accepts a hash of options intermingled with the walk spec options
> rspec ./spec/riak/map_reduce_spec.rb:347 # Riak::MapReduce adding link phases returns self for chaining
> rspec ./spec/riak/beefcake_protobuffs_backend_spec.rb:102 # Riak::Client::BeefcakeProtobuffsBackend secondary index returns no results when no keys or terms are returned
> ```

There were failed tests before my changes, my changed didn't add any new failures. But I had only 3 tests that failed 
```
Finished in 0.70157 seconds (files took 0.57252 seconds to load)
628 examples, 3 failures

Failed examples:

rspec ./spec/riak/map_reduce_spec.rb:370 # Riak::MapReduce adding link phases accepts a hash of options intermingled with the walk spec options
rspec ./spec/riak/map_reduce_spec.rb:347 # Riak::MapReduce adding link phases returns self for chaining
rspec ./spec/riak/beefcake_protobuffs_backend/ts_cell_codec_spec.rb:49 # Riak::Client::BeefcakeProtobuffsBackend::TsCellCodec serializing values refuses to serialize big numbers
```

**Comment by tatsianaclifton** [comment]
I pulled down that branch and also have 3 tests fail not 6. @aenand How to you run tests? I did with `bundle exec rake`. I am wondering if you are running with different command and maybe more tests are included.

**Comment by apfranzen** [comment]
@tatsianaclifton for what it is worth, I am running tests with `bundle exec rake` as well, but I am getting 6 failures, even when running tests on a very old commit like ce831c2b.

**Comment by tatsianaclifton** [comment]
I don't know. I tried to run tests for files with 3 other failures separately and they still pass for me. Anyway, this PR doesn't introduce any new failures, so we don't need to worry about that.

**Review by tatsianaclifton — CHANGES_REQUESTED** [review]
It looks good to me and tests passing rate is the same as for master. The only one additional change we need is a version change for that gem. And then you should created a tag for that version.

**Review by tatsianaclifton — APPROVED** [review]
Great. Thanks

**Review by apfranzen — APPROVED** [review]

**Pull request merged**
